// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'CircleCloseButton': typeof import("../components/CircleCloseButton.vue")['default'],
    'ClickEffects': typeof import("../components/ClickEffects.vue")['default'],
    'DecorationBox': typeof import("../components/DecorationBox.vue")['default'],
    'MenuBtn': typeof import("../components/MenuBtn.vue")['default'],
    'PageDecoration': typeof import("../components/PageDecoration.vue")['default'],
    'YBIMG': typeof import("../components/YBIMG.vue")['default'],
    'MainPageBorder': typeof import("../components/MainPage/Border.vue")['default'],
    'MainPage': typeof import("../components/MainPage/index.vue")['default'],
    'MainPageLogo': typeof import("../components/MainPage/Logo.vue")['default'],
    'MainPageStarAndMoon': typeof import("../components/MainPage/StarAndMoon.vue")['default'],
    'MenuPage': typeof import("../components/MenuPage/index.vue")['default'],
    'Menu': typeof import("../components/MenuPage/Menu.vue")['default'],
    'MenuPageMoveStar': typeof import("../components/MenuPage/MoveStar.vue")['default'],
    'MessageBox': typeof import("../components/MessageBox/index.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyCircleCloseButton': typeof import("../components/CircleCloseButton.vue")['default'],
    'LazyClickEffects': typeof import("../components/ClickEffects.vue")['default'],
    'LazyDecorationBox': typeof import("../components/DecorationBox.vue")['default'],
    'LazyMenuBtn': typeof import("../components/MenuBtn.vue")['default'],
    'LazyPageDecoration': typeof import("../components/PageDecoration.vue")['default'],
    'LazyYBIMG': typeof import("../components/YBIMG.vue")['default'],
    'LazyMainPageBorder': typeof import("../components/MainPage/Border.vue")['default'],
    'LazyMainPage': typeof import("../components/MainPage/index.vue")['default'],
    'LazyMainPageLogo': typeof import("../components/MainPage/Logo.vue")['default'],
    'LazyMainPageStarAndMoon': typeof import("../components/MainPage/StarAndMoon.vue")['default'],
    'LazyMenuPage': typeof import("../components/MenuPage/index.vue")['default'],
    'LazyMenu': typeof import("../components/MenuPage/Menu.vue")['default'],
    'LazyMenuPageMoveStar': typeof import("../components/MenuPage/MoveStar.vue")['default'],
    'LazyMessageBox': typeof import("../components/MessageBox/index.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export const CircleCloseButton: typeof import("../components/CircleCloseButton.vue")['default']
export const ClickEffects: typeof import("../components/ClickEffects.vue")['default']
export const DecorationBox: typeof import("../components/DecorationBox.vue")['default']
export const MenuBtn: typeof import("../components/MenuBtn.vue")['default']
export const PageDecoration: typeof import("../components/PageDecoration.vue")['default']
export const YBIMG: typeof import("../components/YBIMG.vue")['default']
export const MainPageBorder: typeof import("../components/MainPage/Border.vue")['default']
export const MainPage: typeof import("../components/MainPage/index.vue")['default']
export const MainPageLogo: typeof import("../components/MainPage/Logo.vue")['default']
export const MainPageStarAndMoon: typeof import("../components/MainPage/StarAndMoon.vue")['default']
export const MenuPage: typeof import("../components/MenuPage/index.vue")['default']
export const Menu: typeof import("../components/MenuPage/Menu.vue")['default']
export const MenuPageMoveStar: typeof import("../components/MenuPage/MoveStar.vue")['default']
export const MessageBox: typeof import("../components/MessageBox/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const NuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const LazyCircleCloseButton: typeof import("../components/CircleCloseButton.vue")['default']
export const LazyClickEffects: typeof import("../components/ClickEffects.vue")['default']
export const LazyDecorationBox: typeof import("../components/DecorationBox.vue")['default']
export const LazyMenuBtn: typeof import("../components/MenuBtn.vue")['default']
export const LazyPageDecoration: typeof import("../components/PageDecoration.vue")['default']
export const LazyYBIMG: typeof import("../components/YBIMG.vue")['default']
export const LazyMainPageBorder: typeof import("../components/MainPage/Border.vue")['default']
export const LazyMainPage: typeof import("../components/MainPage/index.vue")['default']
export const LazyMainPageLogo: typeof import("../components/MainPage/Logo.vue")['default']
export const LazyMainPageStarAndMoon: typeof import("../components/MainPage/StarAndMoon.vue")['default']
export const LazyMenuPage: typeof import("../components/MenuPage/index.vue")['default']
export const LazyMenu: typeof import("../components/MenuPage/Menu.vue")['default']
export const LazyMenuPageMoveStar: typeof import("../components/MenuPage/MoveStar.vue")['default']
export const LazyMessageBox: typeof import("../components/MessageBox/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
