// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'ClickEffects': typeof import("../components/ClickEffects.vue")['default'],
    'MenuBtn': typeof import("../components/MenuBtn.vue")['default'],
    'MenuPage': typeof import("../components/MenuPage.vue")['default'],
    'MainPageBorder': typeof import("../components/MainPage/Border.vue")['default'],
    'MainPage': typeof import("../components/MainPage/index.vue")['default'],
    'MainPageLogo': typeof import("../components/MainPage/Logo.vue")['default'],
    'MainPageStarAndMoon': typeof import("../components/MainPage/StarAndMoon.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyClickEffects': typeof import("../components/ClickEffects.vue")['default'],
    'LazyMenuBtn': typeof import("../components/MenuBtn.vue")['default'],
    'LazyMenuPage': typeof import("../components/MenuPage.vue")['default'],
    'LazyMainPageBorder': typeof import("../components/MainPage/Border.vue")['default'],
    'LazyMainPage': typeof import("../components/MainPage/index.vue")['default'],
    'LazyMainPageLogo': typeof import("../components/MainPage/Logo.vue")['default'],
    'LazyMainPageStarAndMoon': typeof import("../components/MainPage/StarAndMoon.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export const ClickEffects: typeof import("../components/ClickEffects.vue")['default']
export const MenuBtn: typeof import("../components/MenuBtn.vue")['default']
export const MenuPage: typeof import("../components/MenuPage.vue")['default']
export const MainPageBorder: typeof import("../components/MainPage/Border.vue")['default']
export const MainPage: typeof import("../components/MainPage/index.vue")['default']
export const MainPageLogo: typeof import("../components/MainPage/Logo.vue")['default']
export const MainPageStarAndMoon: typeof import("../components/MainPage/StarAndMoon.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const NuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const LazyClickEffects: typeof import("../components/ClickEffects.vue")['default']
export const LazyMenuBtn: typeof import("../components/MenuBtn.vue")['default']
export const LazyMenuPage: typeof import("../components/MenuPage.vue")['default']
export const LazyMainPageBorder: typeof import("../components/MainPage/Border.vue")['default']
export const LazyMainPage: typeof import("../components/MainPage/index.vue")['default']
export const LazyMainPageLogo: typeof import("../components/MainPage/Logo.vue")['default']
export const LazyMainPageStarAndMoon: typeof import("../components/MainPage/StarAndMoon.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt3/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt3/dist/app/components/client-only")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
